#!/usr/bin/env node

/**
 * Script to add permissions to an existing role
 * Usage: node scripts/add_permissions_to_role.js
 */

const mongoose = require('mongoose');
const path = require('path');

// Load environment variables
require('dotenv').config({ path: path.join(__dirname, '../.env') });

// Import models
const Role = require('../src/api/models/role.model');
const Permission = require('../src/api/models/permission.model');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/fable_backend';

// Define permissions to create/assign
const PERMISSIONS_TO_CREATE = [
  'Master Admin',
  'Operator Create',
  'Operator View',
  'Operator Edit',
  'Operator Delete',
  'Bus Create',
  'Bus View',
  'Bus Edit',
  'Bus Delete',
  'User Create',
  'User View',
  'User Edit',
  'User Delete',
  'Driver Create',
  'Driver View',
  'Driver Edit',
  'Driver Delete',
  'Route Create',
  'Route View',
  'Route Edit',
  'Route Delete',
  'Booking View',
  'Booking Edit',
  'Booking Delete',
  'Dashboard View',
  'Settings View',
  'Settings Edit',
  'Location Create',
  'Location View',
  'Location Edit',
  'Location Delete',
  'City Create',
  'City View',
  'City Edit',
  'City Delete',
  'Country Create',
  'Country View',
  'Country Edit',
  'Country Delete',
  'Currency Create',
  'Currency View',
  'Currency Edit',
  'Currency Delete',
  'Offer Create',
  'Offer View',
  'Offer Edit',
  'Offer Delete',
  'Pass Create',
  'Pass View',
  'Pass Edit',
  'Pass Delete',
  'Payment View',
  'Payment Edit',
  'Wallet View',
  'Wallet Edit',
  'Notification Create',
  'Notification View',
  'Notification Edit',
  'Notification Delete',
  'Upload View',
  'Upload Create',
  'Map View',
  'Map Edit',
  'Bus Schedule Create',
  'Bus Schedule View',
  'Bus Schedule Edit',
  'Bus Schedule Delete',
  'Bus Layout Create',
  'Bus Layout View',
  'Bus Layout Edit',
  'Bus Layout Delete',
  'Bus Type Create',
  'Bus Type View',
  'Bus Type Edit',
  'Bus Type Delete',
  'Route Bus Create',
  'Route Bus View',
  'Route Bus Edit',
  'Route Bus Delete',
  'Timetable Create',
  'Timetable View',
  'Timetable Edit',
  'Timetable Delete',
  'Helper Create',
  'Helper View',
  'Helper Edit',
  'Helper Delete',
  'Referral View',
  'Referral Edit',
  'Suggest View',
  'Suggest Edit',
  'Suggest Delete',
];

async function createPermissions() {
  console.log('Creating/updating permissions...');
  const createdPermissions = [];
  
  for (const permissionName of PERMISSIONS_TO_CREATE) {
    // Check if permission already exists
    let permission = await Permission.findOne({ name: permissionName });
    if (!permission) {
      permission = new Permission({
        name: permissionName,
        // slug will be auto-generated by pre-save middleware
      });
      await permission.save();
      console.log(`✅ Created permission: ${permissionName} (${permission.slug})`);
    } else {
      console.log(`ℹ️  Permission already exists: ${permissionName} (${permission.slug})`);
    }
    createdPermissions.push(permission._id);
  }
  
  return createdPermissions;
}

async function addPermissionsToRole(roleId) {
  try {
    // Connect to MongoDB
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB');

    // Find the role
    const role = await Role.findById(roleId);
    if (!role) {
      console.error(`❌ Role with ID ${roleId} not found`);
      return;
    }

    console.log(`📋 Found role: ${role.name} (${role.slug})`);
    console.log(`📊 Current permissions count: ${role.permissions.length}`);

    // Create all permissions
    const permissionIds = await createPermissions();

    // Update the role with all permissions
    role.permissions = permissionIds;
    await role.save();

    console.log(`✅ Updated role "${role.name}" with ${permissionIds.length} permissions`);

    // Verify the update
    const updatedRole = await Role.findById(roleId).populate('permissions');
    console.log(`📊 Updated permissions count: ${updatedRole.permissions.length}`);

    // Display success message
    console.log('\n🎉 ==========================================');
    console.log('   PERMISSIONS ADDED SUCCESSFULLY');
    console.log('==========================================');
    console.log(`🆔 Role ID: ${roleId}`);
    console.log(`👤 Role Name: ${role.name}`);
    console.log(`🔗 Role Slug: ${role.slug}`);
    console.log(`🔐 Permissions: ${permissionIds.length} permissions assigned`);
    console.log('==========================================\n');

    console.log('You can now test the /v1/auth/access endpoint again.');
    console.log('It should return permissions with length > 0.');

  } catch (error) {
    console.error('❌ Error adding permissions to role:', error.message);
  } finally {
    // Close database connection
    await mongoose.connection.close();
    console.log('🔌 Database connection closed');
  }
}

// Get role ID from command line argument or use the one from your curl request
const roleId = process.argv[2] || '68d03ccfcc6de0b6cc8a3152';

// Run the script
if (require.main === module) {
  console.log(`🎯 Adding permissions to role: ${roleId}`);
  addPermissionsToRole(roleId)
    .then(() => {
      console.log('✅ Script completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Script failed:', error);
      process.exit(1);
    });
}

module.exports = addPermissionsToRole;
