#!/usr/bin/env node

/**
 * Enhanced script to create a sample admin user with permissions
 * Usage: node scripts/create_admin_with_permissions.js
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const path = require('path');

// Load environment variables
require('dotenv').config({ path: path.join(__dirname, '../.env') });

// Import models
const Admin = require('../src/api/models/admin.model');
const AdminDetail = require('../src/api/models/adminDetail.model');
const Role = require('../src/api/models/role.model');
const Permission = require('../src/api/models/permission.model');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/redbus_admin';

// Define permissions to create
const PERMISSIONS_TO_CREATE = [
  'Master Admin',
  'Operator Create',
  'Operator View',
  'Operator Edit',
  'Operator Delete',
  'Bus Create',
  'Bus View',
  'Bus Edit',
  'Bus Delete',
  'User Create',
  'User View',
  'User Edit',
  'User Delete',
  'Driver Create',
  'Driver View',
  'Driver Edit',
  'Driver Delete',
  'Route Create',
  'Route View',
  'Route Edit',
  'Route Delete',
  'Booking View',
  'Booking Edit',
  'Booking Delete',
  'Dashboard View',
  'Settings View',
  'Settings Edit',
];

async function createPermissions() {
  console.log('Creating permissions...');
  const createdPermissions = [];
  
  for (const permissionName of PERMISSIONS_TO_CREATE) {
    // Check if permission already exists
    let permission = await Permission.findOne({ name: permissionName });
    if (!permission) {
      permission = new Permission({
        name: permissionName,
        // slug will be auto-generated by pre-save middleware
      });
      await permission.save();
      console.log(`✅ Created permission: ${permissionName} (${permission.slug})`);
    } else {
      console.log(`ℹ️  Permission already exists: ${permissionName} (${permission.slug})`);
    }
    createdPermissions.push(permission._id);
  }
  
  return createdPermissions;
}

async function createSampleAdmin() {
  try {
    // Connect to MongoDB
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB');

    // Check if admin already exists
    const existingAdmin = await Admin.findOne({ email: 'admin@admin.com' });
    if (existingAdmin) {
      console.log('⚠️  Admin with email admin@admin.com already exists');
      console.log('Admin ID:', existingAdmin._id);
      console.log('Status:', existingAdmin.is_active ? 'Active' : 'Inactive');
      return;
    }

    // Create permissions first
    const permissionIds = await createPermissions();

    // Create admin user
    console.log('Creating admin user...');
    const adminData = {
      email: 'admin@admin.com',
      password: '123456', // This will be hashed by the pre-save middleware
      firstname: 'Super',
      lastname: 'Admin',
      phone: '9876543210',
      role: 'admin',
      picture: 'default.jpg',
      is_active: true,
    };

    const admin = new Admin(adminData);
    await admin.save();
    console.log('✅ Admin user created successfully');

    // Create admin details
    console.log('Creating admin details...');
    const adminDetailData = {
      adminId: admin._id,
      company: 'RedBus Admin Panel',
      address_1: 'Admin Office',
      address_2: 'Main Building',
      city: 'Mumbai',
      pincode: '400001',
      is_agent: false,
      commission: 0,
    };

    const adminDetail = new AdminDetail(adminDetailData);
    await adminDetail.save();
    console.log('✅ Admin details created successfully');

    // Find or create admin role with permissions
    console.log('Setting up admin role with permissions...');
    let adminRole = await Role.findOne({ name: 'admin' });
    if (!adminRole) {
      adminRole = new Role({
        name: 'admin',
        slug: 'admin',
        permissions: permissionIds, // Array of permission ObjectIds
      });
      await adminRole.save();
      console.log('✅ Admin role created with all permissions');
    } else {
      // Update existing role with permissions if it doesn't have them
      if (adminRole.permissions.length === 0) {
        adminRole.permissions = permissionIds;
        await adminRole.save();
        console.log('✅ Updated existing admin role with permissions');
      } else {
        console.log('✅ Using existing admin role with permissions');
      }
    }

    // Assign role to admin
    admin.roleId = adminRole._id;
    await admin.save();
    console.log('✅ Admin role assigned successfully');

    // Display success message
    console.log('\n🎉 ==========================================');
    console.log('   SAMPLE ADMIN CREATED SUCCESSFULLY');
    console.log('==========================================');
    console.log('📧 Email:    admin@admin.com');
    console.log('🔑 Password: 123456');
    console.log('👤 Role:     admin');
    console.log('✅ Status:   Active');
    console.log('🆔 Admin ID:', admin._id);
    console.log('🔐 Permissions:', permissionIds.length, 'permissions assigned');
    console.log('==========================================\n');

    console.log('You can now login to the admin panel using these credentials.');
    console.log('The admin has full access to all system features.');

  } catch (error) {
    console.error('❌ Error creating sample admin:', error.message);
    if (error.code === 11000) {
      console.error('This usually means the email already exists in the database.');
    }
  } finally {
    // Close database connection
    await mongoose.connection.close();
    console.log('🔌 Database connection closed');
  }
}

// Run the script
if (require.main === module) {
  createSampleAdmin()
    .then(() => {
      console.log('✅ Script completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Script failed:', error);
      process.exit(1);
    });
}

module.exports = createSampleAdmin;
